**Описание таблиц Yxxxxx.Такси в формате Markdown**

### `cars`

| Поле  | Описание              | Пример                                                                    |
| ----- | --------------------- | ------------------------------------------------------------------------- |
| `id`  | ID автомобиля         | 1543                                                                      |
| `data`| Данные в JSON-формате | {'марка': 'Toyota', 'модель': 'Camry', 'тариф': 'эконом', 'аренда': 2000} |


### `drivers`

| Поле         | Описание                         | Пример   |
| ------------ | -------------------------------- | -------- |
| `id`         | ID таксиста                      | 532      |
| `first_name` | Имя                              | Артем    |
| `last_name`  | Фамилия                          | Иванов   |
| `auto`       | ID авто                          | 1543     |
| `rating`     | Средний рейтинг (может быть NaN) | 4.6      |
| `city`       | Город Московской области         | Подольск |

### `clients`

| Поле         | Описание                          | Пример    |
| ------------ | --------------------------------- | --------- |
| `id`         | ID клиента                        | 10054     |
| `first_name` | Имя                               | Мария     |
| `last_name`  | Фамилия                           | Кузнецова |
| `city`       | Город                             | Москва    |
| `rating`     | Средний рейтинг (может быть NaN)  | 4.8       |
| `n_orders`   | Количество заказов (может быть 0) | 3         |

### `orders`

| Поле     | Описание                                                   | Пример               |
| -------- | ---------------------------------------------------------- | -------------------- |
| `id`     | ID заказа                                                  | 98541                |
| `data`   | Дата заказа                                                | 2024-10-05           |
| `taxist` | ID или имя таксиста                                        | 532 или "Иванов А."  |
| `client` | ID или имя клиента                                         | 10054 или "Мария К." |
| `r1`     | Оценка водителя (1–5 или проценты, NaN)                    | 80                   |
| `r2`     | Оценка клиента (1–5 или проценты, NaN)                     | 100                  |
| `tariff` | Тариф поездки (может не совпадать с авто, может быть NaN)  | комфорт+ или к+      |
| `len`    | Длина маршрута (км, м или строка с ед.)                    | "12 km"              |
| `time`   | Длительность поездки (мин, сек или строка)                 | "15 min"             |
| `coef`   | Коэффициент стоимости                                      | 1.2                  |
| `cost`   | Итоговая стоимость                                         | 780                  |
| `auto`   | ID авто                                                    | 1543                 |
| `service_fee`| Сервисный сбор компании                                | 156.0                |

In [16]:
import pandas as pd

cars_df = pd.read_csv('cars.csv')
drivers_df = pd.read_csv('drivers.csv')
clients_df = pd.read_csv('clients.csv')
orders_df = pd.read_csv('orders.csv')

In [17]:
orders_df.head(20)

,id,data,taxist,client,r1,r2,tariff,len,time,coef,cost,auto,service_fee
0,1,2024-09-16,151,1,NaN,5.0,эконом,10.0 km,19.0 min,1.09,293,443,58.6
1,2,2024/09/08,511,1,NaN,5.0,эконом,11.7 km,22.0 min,0.92,286,1479,57.2
2,3,2024-09-14,632,1,NaN,5.0,эконом,14.16 km,18.14 min,1.27,387,717,77.4
3,4,2024-09-03,1439,2,NaN,5.0,комфорт,27.6 km,45.0 min,1.37,1597,1241,319.4
4,5,2024-09-19,292,2,5.0,NaN,комфорт,44.6 km,72.33 min,0.92,1737,1646,347.4
5,6,2024-09-02,795,2,5.0,NaN,комфорт,13.0 km,14.1 min,1.06,472,640,94.4
6,7,2024-09-26,331,2,NaN,NaN,эконом,22.0 km,25.7 min,1.16,519,249,103.8
7,8,2024-09-18,725,2,NaN,5.0,эконом,7.0 km,12.58 min,0.85,152,1394,30.4
8,9,04.09.2024,936,3,NaN,NaN,эконом,10.5 km,15.31 min,0.95,231,431,46.2
9,10,2024-09-24,246,3,NaN,NaN,эконом,15.74 km,22.0 min,1.19,424,1564,84.8
10,11,2024-09-11,1170,4,NaN,5.0,комфорт+,46698.0 m,56.49 min,0.81,1618,860,323.6
11,12,2024-09-16,1421,4,NaN,NaN,эконом,36.3 km,62.13 min,1.07,987,1094,197.4
12,13,2024-09-10,1234,4,5.0,NaN,эконом,17.07 km,32.5 min,0.86,398,1601,79.6
13,14,2024-09-03,568,5,NaN,NaN,эконом,21.35 km,37.98 min,1.35,750,873,150.0
14,15,17.09.2024,941,5,NaN,NaN,к+,40.9 km,50.0 min,1.09,1924,597,384.8
15,16,2024-09-03,1042,5,5.0,NaN,эконом,12.58 km,15.0 min,1.27,333,1692,66.6
16,17,2024/09/18,1320,5,NaN,NaN,эконом,35.0 km,52.0 min,1.18,966,1072,193.2
17,18,2024-09-20,1489,5,4.0,NaN,эконом,18.8 km,34.98 min,0.99,498,1357,99.6
18,19,03-Sep-2024,964,6,NaN,4.0,эконом,17.44 km,27.0 min,0.87,363,1307,72.6
19,20,2024-09-09,828,6,4.0,5.0,эконом,6.84 km,8.4 min,0.92,150,723,30.0

In [18]:
cars_df.head(20)

    id                                               data
0    1  {'марка': 'Lada', 'модель': 'Granta', 'тариф':...
1    2  {'марка': 'Daewoo', 'модель': 'Matiz', 'тариф'...
2    3  {'марка': 'Chevrolet', 'модель': 'Spark', 'тар...
3    4  {'марка': 'Mitsubishi', 'модель': 'Outlander',...
4    5  {'марка': 'Volkswagen', 'модель': 'Passat', 'т...
5    6  {'марка': 'Fiat', 'модель': 'Panda', 'тариф': ...
6    7  {'марка': 'Daewoo', 'модель': 'Matiz', 'тариф'...
7    8  {'марка': 'Volkswagen', 'модель': 'Passat', 'т...
8    9  {'марка': 'Fiat', 'модель': 'Panda', 'тариф': ...
9   10  {'марка': 'Hyundai', 'модель': 'Elantra', 'тар...
10  11  {'марка': 'Hyundai', 'модель': 'Elantra', 'тар...
11  12  {'марка': 'Chery', 'модель': 'Tiggo 4', 'тариф...
12  13  {'марка': 'Datsun', 'модель': 'on-DO', 'тариф'...
13  14  {'марка': 'Honda', 'модель': 'Accord', 'тариф'...
14  15  {'марка': 'Ford', 'модель': 'Mondeo', 'тариф':...
15  16  {'марка': 'Kia', 'модель': 'Rio', 'тариф': 'эк...
16  17  {'марка': 'Chevrolet', 'модель': 'Spark', 'тар...
17  18  {'марка': 'Hyundai', 'модель': 'Solaris', 'тар...
18  19  {'марка': 'Nissan', 'модель': 'Qashqai', 'тари...
19  20  {'марка': 'Subaru', 'модель': 'Outback', 'тари...

In [19]:
clients_df.head(20)

    id first_name   last_name             city     rating  n_orders
0    1    Наталья    Аксенова     Долгопрудный   5.000000         3
1    2    Тимофей       Рябов         Подольск   4.000000         5
2    3       Глеб     Тетерин          Королев   3.500000         2
3    4     Никита      Пестов          Люберцы   5.000000         3
4    5      Алёна     Крюкова          Люберцы   4.200000         5
5    6     Андрей     Беляков     Долгопрудный   4.500000         2
6    7      Демид      Орехов            Химки   3.666667         3
7    8      Арина   Субботина            Химки   5.000000         7
8    9      Диана       Зуева     Долгопрудный   3.666667         4
9   10    Наталья     Карпова     Долгопрудный   5.000000         4
10  11    Алексей       Туров          Королев  22.750000         5
11  12     Андрей    Шестаков            Химки   5.000000         1
12  13     Максим    Савельев           Мытищи   5.000000         2
13  14     Виктор    Воробьев           Реутов  24.000000         6
14  15      Мария   Некрасова          Королев   3.800000         5
15  16     Полина  Пономарева          Королев   4.500000         2
16  17     Михаил    Федосеев     Долгопрудный   5.000000         4
17  18       Глеб    Филиппов           Мытищи   3.000000         2
18  19      Артем     Дроздов           Реутов   5.000000         4
19  20    Ярослав     Дьячков  Железнодорожный   3.000000         7

In [20]:
drivers_df.head(20)

    id first_name   last_name  auto    rating             city
0    1  Нурсултан      Жумаев  1494  5.957447           Реутов
1    2     Шамиль  Абдурахман  1798  6.552326           Москва
2    3      Мурад  Абдурахман   850  6.529412  Железнодорожный
3    4     Рустам     Назаров   940  7.310757     Долгопрудный
4    5    Дильшод     Касымов  1439  5.440994           Москва
5    6       Саид      Юсупов   641  5.913386           Мытищи
6    7      Сафия     Багаева  1013  6.217899            Химки
7    8    Магомед     Гаджиев   287  6.028169           Москва
8    9      Лейла    Шарипова   596  5.907950           Москва
9   10   Темирлан     Каримов  1600  6.626943           Мытищи
10  11      Гамид      Караев   247  7.681159         Балашиха
11  12       Зара    Гаджиева  1305  9.088889           Москва
12  13    Дильшод      Алимов   345  7.925094          Люберцы
13  14     Эльнур     Назаров   784  6.379464     Долгопрудный
14  15     Рустам      Жумаев  1467  5.975758           Москва
15  16     Фатима     Саидова   414  6.066667           Москва
16  17    Рамазан     Шарипов  1723  7.744186           Москва
17  18    Рамазан      Юсупов   891  6.919149           Москва
18  19      Мурад      Багаев   391  6.148837           Москва
19  20     Рустам      Саидов  1262  5.547170           Москва